version: "3.1"
name: tradeport_clone
services:
  mysql:
    image: mysql:latest
    container_name: mysql_instance
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: tradeport
    ports:
      - 3306:3306
volumes:
  mysql_data:
